_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 35
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 11
                - 35
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
detr_dim:
    value: 128
epochs:
    value: 200
extra_layers:
    value: "True"
freeze_backbone:
    value: "False"
freeze_bbox_predictor:
    value: "False"
freeze_transformer:
    value: "False"
img_size:
    value: 256
lr:
    value: 0.2
momentum:
    value: 0.95
optimizer:
    value: RMSprop
trial.number:
    value: 0
