path: /home/xavier/Projects/MasterCV/C6_Lab/Week3/dataset  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images ('relative to path')

# Classes
names:
  0: car